# Generated by Django 5.0.6 on 2024-05-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="inventory",
            field=models.SmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="menu",
            name="item",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
